// <auto-generated />
namespace JM.Business.Kontakt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class LastEditDatealsnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastEditDatealsnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201407300941171_LastEdit-Date als nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
