// <auto-generated />
namespace JM.Business.Kontakt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AnredefürBenutzerhinzugefügt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnredefürBenutzerhinzugefügt));
        
        string IMigrationMetadata.Id
        {
            get { return "201407310716446_Anrede für Benutzer hinzugefügt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
