//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.BaseSolutionWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JM.BaseSolutionWizard.Properties.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; was found in more than one assembly ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_AmbiguousTypeMatch {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_AmbiguousTypeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transform and Locator attributes must contain only a type name, or a type name followed by a list of attributes in parentheses. ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_BadAttributeValue {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_BadAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal syntax error ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_FatalTransformSyntaxError {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_FatalTransformSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import tag cannot have both a &apos;path&apos; and an &apos;assembly&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportAttributeConflict {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportAttributeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import tag must have a &apos;path&apos; or an &apos;assembly&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportMissingAssembly {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportMissingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import tag must have a &apos;namespace&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportMissingNamespace {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import tag does not support &apos;{0}&apos; attribute ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_ImportUnknownAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_ImportUnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a type of {1} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_IncorrectBaseType {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_IncorrectBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No element in the source document matches &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertBadXPath {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertBadXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; does not evaluate to an element ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertBadXPathResult {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertBadXPathResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} requires an XPath argument ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertMissingArgument {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertMissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many arguments to {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_InsertTooManyArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_InsertTooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No attribute &apos;{0}&apos; exists for the Match Locator ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_MatchAttributeDoesNotExist {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_MatchAttributeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; must have a no-argument constructor to be instantiated by the transformation engine ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_NoValidConstructor {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_NoValidConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} requires exactly {1} arguments ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_RequiresExactArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_RequiresExactArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} requires at least {1} arguments ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_RequiresMinimumArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_RequiresMinimumArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many arguments for {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TooManyArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument &apos;{0}&apos; did not match any attributes ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformArgumentFoundNoAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformArgumentFoundNoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformBeginExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformBeginExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} does not expect arguments; ignoring ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformDoesNotExpectArguments {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformDoesNotExpectArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done executing {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformEndExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformEndExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformErrorExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformErrorExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inserted &apos;{0}&apos; element ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageInsert {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No attributes found to remove ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageNoRemoveAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageNoRemoveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No attributes found to set ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageNoSetAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageNoSetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removed &apos;{0}&apos; element ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemove {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removed &apos;{0}&apos; attribute ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemoveAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemoveAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removed {0} attributes ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageRemoveAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageRemoveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replaced &apos;{0}&apos; element ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageReplace {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set &apos;{0}&apos; attribute ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageSetAttribute {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageSetAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set {0} attributes ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformMessageSetAttributes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformMessageSetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (transform line {1}, {2}) ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNameFormatLong {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNameFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNameFormatShort {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNameFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No element in the source document matches &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNoMatchingTargetNodes {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNoMatchingTargetNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not executing {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformNotExecutingMessage {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformNotExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found multiple target elements, but the &apos;{0}&apos; Transform only applies to the first match ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformOnlyAppliesOnce {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformOnlyAppliesOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; did not find a match, because matching nodes in the source document were modified or removed by a previous transform ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformSourceMatchWasRemoved {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformSourceMatchWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applying to &apos;{0}&apos; element (source line {1}, {2}) ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusApplyTarget {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusApplyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applying to &apos;{0}&apos; element (no source line info) ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusApplyTargetNoLineInfo {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusApplyTargetNoLineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on {0} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_TransformStatusXPath {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_TransformStatusXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not resolve &apos;{0}&apos; as a type of {1} ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_UnknownTypeName {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_UnknownTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown tag &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string XMLTRANSFORMATION_UnknownXdtTag {
            get {
                return ResourceManager.GetString("XMLTRANSFORMATION_UnknownXdtTag", resourceCulture);
            }
        }
    }
}
